### ISSUE TITLE
decryption script not working

### ISSUE THREAD

**Issue by rennaMAhcuS** [nagabhavyasree/nnbscryp#1]
The script for the **encryption program is functioning** as expected, but the **`decryption script.py` is not working** as expected. Some improvements:
- Try to **correct the decryption script**.
- Try to take the input for the **`key`** as a **`string`** for both scripts.
- Try to output the key as a **matrix**, as mentioned in the **Problem Statement**.
- You could also try to **output all the possible keys** for a given case.

> [!NOTE]
> These are just some minor suggestions from my side 🙂.

**Mohana, CSeC CTM**

**Comment by nagabhavyasree** [comment]
so,can i resubmit it after doing some changes

**Comment by nagabhavyasree** [comment]
And I was actually not officially registered for this , but I would like to
join. Can you pls add me in the msteams of this course

**Comment by rennaMAhcuS** [comment]
Sure. I will add you. Just complete the errors and submit them along with the second part of the project. I am closing this issue.

**Comment by nagabhavyasree** [comment]
Thank you, I will do that.
